# Jekyll 配置
title: Yihan's Docs
description: 李溢涵的项目文档站点
baseurl: "/HY-LiYihan"
url: "https://hy-liyihan.github.io"

# Markdown 解析
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 默认布局
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# 插件（GitHub Pages 白名单）
plugins:
  - jekyll-seo-tag

# 排除不需要处理的文件
exclude:
  - Chinese_CV.md
  - English_CV.md
